# Generated by Django 6.0.6 on 2026-07-14 00:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customerid', models.CharField(max_length=255, unique=True)),
                ('customername', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orgid', models.CharField(max_length=255, unique=True)),
                ('orgname', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('networkproviderid', models.CharField(max_length=255, unique=True)),
                ('networkprovidername', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networkprovider_customers', to='cdr.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mno',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mnoid', models.CharField(max_length=255, unique=True)),
                ('mnoname', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mno_organizations', to='cdr.organization')),
            ],
            options={
                'verbose_name': 'Mno(Mobile Network Operator)',
                'verbose_name_plural': 'Mnos(Mobile Network Operator)',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_customers', to='cdr.organization'),
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priceplanid', models.CharField(max_length=255, unique=True)),
                ('priceplanname', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priceplan_customers', to='cdr.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thingsgroupid', models.CharField(max_length=255, unique=True)),
                ('thingsgroupname', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='things_customers', to='cdr.customer')),
            ],
            options={
                'verbose_name': 'Dispositivo(Thing)',
                'verbose_name_plural': 'Dispositivos(Things)',
            },
        ),
    ]
