# Generated by Django 6.0.6 on 2026-07-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['imsi']},
        ),
        migrations.RemoveField(
            model_name='device',
            name='msisdn',
        ),
    ]
