# Generated by Django 6.0.6 on 2026-07-14 00:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imsi', models.CharField(max_length=255, verbose_name='IMSI(Internacional Mobile Subscriber Identity)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('status', models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imsi', models.CharField(max_length=255, verbose_name='IMSI(Internacional Mobile Subscriber Identity)')),
                ('realusage', models.CharField(max_length=255, verbose_name='RealUsage1(consumo real)')),
                ('uom', models.CharField(max_length=255, verbose_name='UOM(Unidade de Medida, ex: MB, KB)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
